### ISSUE TITLE
account_key mismatch after changing passwords

### ISSUE THREAD

**Issue by nylen** [wesabe/pfc#1]
Commit dc2b500b5ce242b02103d5cc72b37a0a5cb626d3 removed the code to update the account_key when a user changes their password.  However, User#authenticated_by is still called on each login.  This changes the account_key in the user table but not in the accounts table, which makes wesabe unable to find any accounts or transactions.  Should be reproducible by changing password, logging out, and logging back in.

**Comment by eventualbuddha** [comment]
Fix that changing the password would disconnect accounts. Closed by 361d28a288d3ebfce363073f946ac8a1c4b9a046.
