### ISSUE TITLE
thor importer script fails while setting 'options[:verbose]'

### ISSUE THREAD

**Issue by leogomes** [wesabe/pfc#10]
By running this: 
<code>
thor snapshot:import /home/leo/wesabe/snapshot/lgomes.zip 
</code>
I'm getting the following exception:
<code>
/usr/lib/ruby/gems/1.8/gems/thor-0.14.0/lib/thor/core_ext/hash_with_indifferent_access.rb:26:in `[]=': can't modify frozen hash (TypeError)
    from /usr/lib/ruby/gems/1.8/gems/thor-0.14.0/lib/thor/core_exy/hash_with_indifferent_access.rb:26:in`[]='
    from /home/leo/wesabe/pfc/lib/tasks/snapshot.thor:10:in `import'
    from /usr/lib/ruby/gems/1.8/gems/thor-0.14.0/lib/thor/task.rb:22:in`send'
</code>

To make it work, I simply commented out the line
<code>#    options[:verbose] = !options[:quiet]</code>

**Comment by eventualbuddha** [comment]
This was fixed in ee3e08f045cfa06c955cd97f1f98476b6419d45a.

**Comment by leogomes** [comment]
Are you sure? I think it's actually what introduced the issue :)

I'm not a Ruby expert, nor did I really read much about Thor, but I'm under the impression that the options hash is created when you do:
<code>
method_options %w(quiet -q)    => false
method_options %w(email -u)    => :string
method_options %w(password -p) => :string
</code>
and when you try to assign:
<code>options[:verbose] = !options[:quiet]</code>
you're actually trying to modify a frozen hash, and then comes the issue I'm facing.

Maybe options[:verbose] is defined at the parent class (Thor) and there's something I'm not seeing here...

Cheers,
Leo.

**Comment by eventualbuddha** [comment]
Whoops, you're right. I meant f26e9212ece7d83b2744a5129b4c9d071fe94c25.
