### ISSUE TITLE
The uploads tmp dir isn't automatically created so statement uploads fail.

### ISSUE THREAD

**Issue by jonisbell** [wesabe/pfc#11]
Fix: create temp dir on statement upload - if it doesn't already exist

http://github.com/jonisbell/pfc/commit/911021ef7d436ec5d3f6335de0fa1b8d50f8ef94

**Comment by jonisbell** [comment]
To clarify this occurs when uploading a QIF during the account creation process, it probably occurs at other points. The tmp directory doesn't exist. See commit in previous message for a quick fix, there is probably a better one.

Exception:
cannot generate tempfile `/home/wesabe/pfc/private/wesabe/uploads/tmp/upload20100821-12033-yqz2y6-9'

Stack Trace:
lib/tempfile_path.rb:13:in `new'
lib/tempfile_path.rb:13:in`initialize'
lib/tempfile_path.rb:27:in `new'
lib/tempfile_path.rb:27:in`generate'
app/controllers/uploads_controller.rb:151:in `create'

**Comment by carlosbislip** [comment]
I have recently used this to create new accounts.

**Comment by eventualbuddha** [comment]
Pulled as 5e0fa05418a5212e1df368891367ce488634f4c9, thanks.
