### ISSUE TITLE
Need to remove charguess as a required gem after adding it to bundler

### ISSUE THREAD

**Issue by jmilum** [wesabe/pfc#12]
After merging commit 079ebf79ffaa6b5316348b843e266271de7f9c19 I got this error:

```
=> Booting Mongrel
=> Rails 3.0.0.beta4 application starting in development on http://0.0.0.0:3000
=> Call with -d to detach
=> Ctrl-C to shutdown server
Exiting
/Users/jeremy/.bundle/ruby/1.8/gems/activesupport-    3.0.0.beta4/lib/active_support/dependencies.rb:212:in `require': no such file to load -- charguess     (LoadError)
```

I was able to solve the issue by removing the requirement for charguess from the 01 initializer with this commit: df3c1cd5eccf04724871d763841cbd32a506ce11

**Comment by eventualbuddha** [comment]
Did you run `bundle install` again?

**Comment by jmilum** [comment]
Ahhh, you are right. I must not have. after reverting this commit and running bundle install the error was not repeatable.
