### ISSUE TITLE
Default currency should be smarter

### ISSUE THREAD

**Issue by eventualbuddha** [wesabe/pfc#15]
The user's default currency is currently set by selecting a country in the signup screen. This is an optional field and is not obviously going to set your currency. Something should be done to improve this.

**Suggestion:** Don't set the user's default currency at all, but instead wait until there is an account being created. The user should then adopt that currency as their default currency if they haven't already set it manually. Note that this will complicate certain types of account creation, such as Cash/Manual & uploads via files that don't contain currency info (i.e. QIF).

**Comment by 1nnovate** [comment]
User default currency doesn't appear to be set by selecting the country in the signup screen. Suggestion is a good idea.

**Comment by eventualbuddha** [comment]
Seems Good Enough™ after applying the patch to add default currency to the signup page.
