### ISSUE TITLE
Crash on going to url like /accounts/1

### ISSUE THREAD

**Issue by nylen** [wesabe/pfc#16]
I was getting a crash similar to:

```
method `split' called for 1:Fixnum (NoMethodError)
```

when attempting to navigate to the url /accounts/1 (or similar) in pfc.  The following fixed it for me: nylen@1b3f59f83e1b5cbe5ae64e00bd2b1eeccd064416

**Comment by eventualbuddha** [comment]
Make going to /accounts/1 work. Closed by c1c53f551b6c084240f6af4576533b5e27c3081b.
