### ISSUE TITLE
ChildLabor hangs when I upload a statement file

### ISSUE THREAD

**Issue by nylen** [wesabe/pfc#17]
I was experiencing a complete freeze of pfc when I uploaded a statement file.  It was ChildLabor's fault so I changed it back to popen for now (even though that removes the capability to capture stdout and stderr separately).

Here's the commit: nylen@02f001d4da2bf8372eb51c689095587cb43c44e4

I know there were some subprocess handling improvements in ruby 1.9, so it may also be relevant that I'm still on ruby 1.8.7.

**Comment by eventualbuddha** [comment]
I'm also on 1.8.7. Does this happen on every statement upload or just particular ones?

**Comment by jmilum** [comment]
I am having this same error.

**Comment by eventualbuddha** [comment]
Verified. I'll apply your patch if I can't figure it out quickly.

**Comment by eventualbuddha** [comment]
Fixed in 6cde49b3f3220f1ec200af08ec9251cde8ee445f.
