### ISSUE TITLE
New Transfer popup boxes all popup at once and won't dismiss

### ISSUE THREAD

**Issue by jmilum** [wesabe/pfc#18]
After I pulled 66101bb2b09b5822345bc3b35fbe0e2216f32747 I have been getting an intermittent error where the new transfer popup boxes all open at once (for any transaction I have marked as a transfer on the page) and I have no way to dismiss them. It happened once after I marked a transaction as a transfer.

Here is a screencap:

http://www.flickr.com/photos/jmilum/4887144958/

**Comment by jmilum** [comment]
Just tested it again: when I mark a transaction as a transfer and then hit save, as soon as the transfer actually registers (takes a second) the popup box of that transaction appears as well as any other popup box for transactions already marked as transfers on the page. The only way to dismiss them is to reload the page.

**Comment by jmilum** [comment]
Oh, even worse, if I just edit and save any transaction they all popup. The transaction doesn't have to be a transfer.

**Comment by eventualbuddha** [comment]
Will investigate. Sorry about this, I really ought to be testing this stuff better.

**Comment by eventualbuddha** [comment]
Fixed in 4ae45c59f46b24c464457e0ce4ec19ad5cfa6251.

**Comment by jmilum** [comment]
Confirmed. Thanks!
