### ISSUE TITLE
Missing route for deleting a tag

### ISSUE THREAD

**Issue by nylen** [wesabe/pfc#19]
I get the following message in the pfc output when attempting to delete a tag:

```
Started GET "/transactions/rational/bills.xml?start_date=20100212&filter_transfers=true&compact=true&currency=USD&type=spending" for 127.0.0.1 at Thu Aug 12 23:11:27 -0400 2010

ActionController::RoutingError (No route matches "/transactions/rational/bills.xml"):
```

An `alert()` also comes up that shows the HTML for the Rails error page.

**Comment by eventualbuddha** [comment]
Allow deleting tags again. Closed by d3474db5dee84e3ba98fe79c82684905fff1a412.
