### ISSUE TITLE
Missing route for viewing a tag from the pie chart

### ISSUE THREAD

**Issue by nylen** [wesabe/pfc#20]
I just discovered how the pie charts on the main page expand into a sub-piechart when you click on "other tags."  Very cool feature.

However, I get the following error in the pfc output when I try to click on a tag in the pie chart to load its transactions:

```
Started GET "/transactions/rational/bills.xml?start_date=20100212&filter_transfers=true&compact=true&currency=USD&type=spending" for 127.0.0.1 at Thu Aug 12 23:11:27 -0400 2010

ActionController::RoutingError (No route matches "/transactions/rational/bills.xml"):
```

**Comment by eventualbuddha** [comment]
Fix the pie-chart drill-down. Closed by d96e6de30a4279f67b7132990eb6eb44ef7b1f27.
