### ISSUE TITLE
Can't add manual transactions to cash accounts

### ISSUE THREAD

**Issue by jonisbell** [wesabe/pfc#22]
Clicking "add transaction" in a cash account fails. The following error appears in the Javascript console:

Error: widget is undefined
Source File: https://xxx/javascripts/wesabe/views/account-transactions.js?1282385567
Line: 633

```
    $('.date-edit', edit_box).datepicker()
      .val(wesabe.lang.date.format(widget.getDate(), 'yyyy-MM-dd'));
```

**Comment by carlosbislip** [comment]
can you edit recently uploaded check transactions?

**Comment by meleyal** [comment]
yes, editing works for me. only manually adding is broken.

**Comment by joerayme** [comment]
I also have this problem - it would seem that the add transaction button's container (#transactions-header) isn't getting the $.data('widget') set on it. The other containers for the transactions get it set on line 302 of account-transactions.js, but I can't figure out how that gets called. I'll have a proper look this weekend.

**Comment by meleyal** [comment]
I came to the same conclusion, `self.data('widget')` is undefined for the `div#transactions-header.two-col-list` element passed to `startEdit()` at around line 596.

The line which sets up the widgets is `self.data('widget', new wesabe.views.widgets.transactions.Transaction(self));` in the `transaction` method.

Any progress?

**Comment by joerayme** [comment]
I fixed it: see http://github.com/wesabe/pfc/pull/29

**Comment by meleyal** [comment]
Thanks josno, it works :)

**Comment by eventualbuddha** [comment]
Pulled josno's fix.
