### ISSUE TITLE
Check/Cheque transaction is not editable

### ISSUE THREAD

**Issue by ali5h** [wesabe/pfc#27]
When I upload new transactions, Check/Cheque transactions cannot be edited or tagged.

**Comment by carlosbislip** [comment]
i have had this problem for over a month

**Comment by capoferro** [comment]
I also have this issue.

**Comment by eventualbuddha** [comment]
Track transaction URI instead of id. Closed by 29d624cd2c51a1c731146800aebbb996372e10ad.
