### ISSUE TITLE
Statement importing fails unless links are made to fixofx lib and 3rdparty directories 

### ISSUE THREAD

**Issue by jmilum** [wesabe/pfc#3]
I got the following error printed out to the rails terminal when trying to import a statement:

```
fixofx failed importing UNKNOWN statement from Bank (us-000840) with MakeOFX2::FatalError [filepath:  /var/wesabe/uploads/current/014/b9f/014b9fa772160bb3c06867f45388babd3fe7d723aa483f6ed416263f  76d41350/20100724000124-01.dat]
```

I was able to fix the problem by linking to the module directories in the fixofx directory from the pfc dirctory:

```
$ ln -s ../fixofx/3rdparty/ 3rdparty
$ cd lib
$ ln -s ../../fixofx/lib/* .
```

The import then worked correctly

**Comment by eventualbuddha** [comment]
Is this still a problem with the fixed-up fixofx? If it is, please create a ticket on that repo.

**Comment by jmilum** [comment]
Yes it is still a problem. I was unsure where to create the issue, but I will open one there instead.
