### ISSUE TITLE
My Accounts sidebar and transaction lists broken

### ISSUE THREAD

**Issue by douglaswth** [wesabe/pfc#33]
After a recent pull the My Accounts sidebar and transaction lists do not contain anything.

When loading the pages the following error message appears one or two times:

```
/javascripts/wesabe/data/credentials/CredentialDataSource.js?1288573512:20
Uncaught TypeError: Object #<an Object> has no method 'hasData'
```

**Comment by carlosbislip** [comment]
it hangs, and displays the processing circle, without ever displaying anything.
I do get the sidebar though, only transaction data does not display

**Comment by eventualbuddha** [comment]
Are you guys still having this issue? What browser are you using?

**Comment by carlosbislip** [comment]
i stopped having this issues as soon as you made the next  batch of commits

**Comment by eventualbuddha** [comment]
Cool, thanks for confirming.

**Comment by douglaswth** [comment]
I just pulled in from the wesabe master and this seems to be still affecting me, I am using Google Chrome. It also seems to be affecting Firefox.

**Comment by eventualbuddha** [comment]
@douglaswth: I'm not sure how to reproduce this. I've tried creating a totally new account and I'm not seeing this error in either Firefox or Google Chrome.

**Comment by nylen** [comment]
douglaswth: I ran a compare between wesabe/master and your master branch.  I'm not entirely sure why, but it looks really messy:

https://github.com/nylen/pfc/compare/upstream-master...douglaswth-master

You might want to start over from the latest code and just cherry-pick the 3 or so commits where your branch diverges legitimately (at the top of the compare listing).

**Comment by douglaswth** [comment]
I must have reversed a merge or something; I've gotten it working again.

**Comment by eventualbuddha** [comment]
Good to hear!
