### ISSUE TITLE
Deleting Accounts

### ISSUE THREAD

**Issue by carlosbislip** [wesabe/pfc#35]
Password is not recognized when deleting an account. A 403 Forbidden message is shown in PFC terminal.

To delete account go to -->  /pfc/app/controllers/accounts_controller.rb
and comment out (around Line 30):
    "# require correct password to delete an account
       if not current_user.valid_password?(params[:password])
          return render :text => "Incorrect password", :status => :forbidden
       end"
Wesabe will respond with a "Sorry, something has gone wrong." message, and after a page refresh, the account will be no more.

**Comment by eventualbuddha** [comment]
Stop requiring a password to delete accounts. Closed by 5f8860b0f2af1360c77bc96f7f317aa8cbc16c8c.
