### ISSUE TITLE
How to start in standalone mode?

### ISSUE THREAD

**Issue by meleyal** [wesabe/pfc#37]
I saw a standalone mode was added in wesabe/pfc@6003ac8600f6d4bdb695, but how / where do you configure it?

**Comment by carlosbislip** [comment]
does it mean you dont have to manually start brcm?

**Comment by meleyal** [comment]
yes, in `config/initializers/services_config.rb` it says:

> If you're running this as a personal copy on your own machine, you can start with 
> STANDALONE=1 to bring up the necessary services automatically.

**Comment by eventualbuddha** [comment]
You use an environment variable. So, for example, if you're starting the server in `bash` you can use this command:

```
bash$ STANDALONE=1 script/rails server
```

**Comment by meleyal** [comment]
Thanks! Is it possible to put this somewhere in a config file so you don't always have to specify it?

**Comment by eventualbuddha** [comment]
I don't personally need that, but if you want to submit a patch I'd look at it.
