### ISSUE TITLE
New install doesn't work under Firefox

### ISSUE THREAD

**Issue by chunter2** [wesabe/pfc#40]
When I go to http://localhost:3000 Firefox tried to load the page but then adds #/signup over and over again to the url without displaying the signup page.  Google Chrome seems to work but IE fails.  I'm using Firefox 3.6.13 under windows and Ubuntu with the latest pfc running on Ubuntu.

**Comment by nylen** [comment]
This bug is still present, and it seems to be a showstopper for anyone using Firefox.

**Comment by nylen** [comment]
The commit that caused the bug: a2994ad61d451811a4efd7425d34e27a961d70ce

**Comment by eventualbuddha** [comment]
Use a different/better history manager, closed by bf8d2f4ab791eae640f1f41b84002b396bdeee7a.
