### ISSUE TITLE
Permissions issues when running in the development environment

### ISSUE THREAD

**Issue by jmilum** [wesabe/pfc#8]
There are permissions issues when running under the development environment because files are saved to /var/wesabe

I modified that to save everything to Rails.root/private/wesabe when running under the development environment

Also this commit moves the 99 check for fixofx.py into 08_fix_ofx_config.rb, where there other fixofx.py already exist (which will simply the upload configuration, the wiki will need to be modified as well):

http://github.com/jmilum/pfc/commit/10aa8cbed7d2d16d6dfa6f2ac2d9468522ae9562

**Comment by indirect** [comment]
pulled, thanks!
